theme: jekyll-theme-minimal
title: Ideas of software programing's homepage
description: This page is for analyzing terms, patterns, architectures in software. Analyzing the implementations of those and any best practices implementations of best senior developers that you have seen but not understand the idea behind them clearly!
